from __future__ import annotations

import hashlib
import json
import os
from typing import Any

import httpx

FAKE_MODELS = [
    "granite4:1b",
    "granite4:3b",
    "gemma3:1b",
    "gemma3:4b",
    "qwen3:8b",
    "deepseek-r1:7b",
    "fake-model",
]

OLLAMA_BASE_URL = "http://localhost:11434"
CHAT_TIMEOUT_SECONDS = 300.0


async def get_models() -> tuple[list[str], str]:
    """Fetches available local models from Ollama."""
    if os.environ.get("OLLAMA_FAKE"):
        return list(FAKE_MODELS), ""
    try:
        async with httpx.AsyncClient(timeout=3.0) as client:
            response = await client.get(f"{OLLAMA_BASE_URL}/api/tags")
            response.raise_for_status()
            data = response.json()
            models = [model["name"] for model in data.get("models", [])]
            return models, ""
    except httpx.ConnectError:
        return [], "Ollama is not running or unreachable at localhost:11434."
    except Exception as e:
        return [], f"Error fetching models: {str(e)}"


async def chat(
    model: str, message: str, temperature: float = 0.1
) -> tuple[dict[str, Any], dict[str, Any], str]:
    """
    Sends a chat request to Ollama.
    Returns (response_data, request_summary, error_message).
    """
    request_payload = {
        "model": model,
        "messages": [{"role": "user", "content": message}],
        "stream": False,
        "options": {"temperature": temperature},
    }

    request_summary = {"endpoint": "/api/chat", "payload": request_payload}

    if os.environ.get("OLLAMA_FAKE"):
        digest = hashlib.sha256(message.encode("utf-8")).hexdigest()[:12]
        lower = message.lower()
        if "gold json:" in lower or "return json only" in lower:
            fake_content = json.dumps(
                {
                    "overall_pass": True,
                    "grounded_in_evidence": True,
                    "answers_question": True,
                    "rationale": "OLLAMA_FAKE grader pass",
                }
            )
        elif "document context" in lower or "user question" in lower:
            fake_content = (
                f"Mock answer {digest}. "
                "This response is generated by OLLAMA_FAKE for deterministic CI runs."
            )
        elif "summary" in lower and "whatsapp" in lower:
            fake_content = "Mock WhatsApp summary."
        else:
            fake_content = f"Mock response {digest}."

        return (
            {
                "model": model or "fake-model",
                "created_at": "2026-04-12T00:00:00Z",
                "done": True,
                "total_duration": 1,
                "message": {"content": fake_content},
            },
            request_summary,
            "",
        )

    try:
        async with httpx.AsyncClient(timeout=CHAT_TIMEOUT_SECONDS) as client:
            response = await client.post(f"{OLLAMA_BASE_URL}/api/chat", json=request_payload)
            response.raise_for_status()
            data = response.json()
            return data, request_summary, ""
    except httpx.ConnectError:
        return {}, request_summary, "Ollama is not running or unreachable at localhost:11434."
    except httpx.TimeoutException:
        return {}, request_summary, "Ollama request timed out after 5 minutes."
    except Exception as e:
        return {}, request_summary, f"Ollama request failed: {str(e)}"
